name: macro_budget_meal_planner
description: "A meal planning app that optimizes both macros and budget"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  flutter_localizations:
    sdk: flutter

  # Database & Storage
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.0
  sqlite3: ^2.9.0
  path_provider: ^2.1.2
  path: ^1.8.3
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.1.2

  # JSON Serialization
  json_annotation: ^4.8.1

  # Routing
  go_router: ^12.1.3

  # Billing & Monetization
  in_app_purchase: ^3.1.11
  in_app_purchase_android: ^0.3.0+18

  # UI & Material Design
  dynamic_color: ^1.7.0

  # Utilities
  intl: ^0.20.2
  equatable: ^2.0.5
  uuid: ^4.2.1
  share_plus: ^7.2.2
  meta: ^1.11.0
  archive: ^3.6.1
  mobile_scanner: ^3.5.7
  connectivity_plus: ^6.0.5
  package_info_plus: ^8.0.2
  device_info_plus: ^11.0.0
  screenshot: ^2.1.0
  image_picker: ^1.1.2

  # Optional Firebase upload for feedback (add in your env if needed)
  # cloud_firestore: ^5.x.x
  # firebase_storage: ^13.x.x

  # Firebase (telemetry)
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.4

  # Optional Sentry (guarded by USE_SENTRY)
  sentry_flutter: ^8.8.0

  # Cook Mode v2 additions
  wakelock_plus: ^1.2.6
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5
  vibration: ^1.9.0
  percent_indicator: ^4.2.3
  visibility_detector: ^0.4.0+2

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  drift_dev: ^2.14.1

  # Testing
  mocktail: ^1.0.3

  # Linting
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
